In [1]:
import pandas as pd
import numpy as np
np.seterr(divide='ignore', invalid='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [2]:
ratings = pd.read_csv("ratings.csv")
ratings_split = pd.DataFrame(ratings["UserId:ItemId"].str.split(':').tolist(),columns = ['UserId','ItemId'])
ratings["UserId"] = ratings_split["UserId"]
ratings["ItemId"] = ratings_split["ItemId"]
ratings.drop(columns="UserId:ItemId", inplace=True)
# ratings.set_index("UserId",inplace=True)
# ratings.head()
ratings.isnull().sum()


Prediction    0
Timestamp     0
UserId        0
ItemId        0
dtype: int64

In [3]:
targets = pd.read_csv("targets.csv")
targets_split = pd.DataFrame(targets["UserId:ItemId"].str.split(':').tolist(),columns=["UserId","ItemId"])
targets["UserId"] = targets_split["UserId"]
targets["ItemId"] = targets_split["ItemId"]
targets.drop(columns="UserId:ItemId", inplace=True)
targets.set_index("UserId",inplace=True)

# targets.head()
targets.isnull().sum()

ItemId    0
dtype: int64

In [4]:
ratings.head()

Prediction   Timestamp    UserId    ItemId
0           6  1362062307  u0026762  i2171847
1           8  1362062624  u0026502  i0444778
2           6  1362062838  u0004598  i1411238
3           7  1362063503  u0031317  i1496422
4           5  1362063653  u0024257  i0118799

In [5]:
targets.head()

ItemId
UserId            
u0000039  i0060196
u0000039  i0099077
u0000039  i0102926
u0000039  i0109830
u0000039  i0113277

In [6]:
ratings["count_item_apperances"] = ratings.groupby("ItemId")["ItemId"].transform('count')
ratings["count_user_apperances"] = ratings.groupby("UserId")["UserId"].transform('count')
ratings = ratings.loc[(ratings["count_item_apperances"] > 10) | (ratings["ItemId"].isin(targets["ItemId"].unique().tolist()))]
ratings = ratings.loc[(ratings["count_user_apperances"] > 10) | (ratings["UserId"].isin(targets.index.unique().tolist()))]

In [7]:
len(ratings["ItemId"].unique().tolist())

7266

In [8]:
len(targets["ItemId"].unique().tolist())

9698

In [9]:
ratings

Prediction   Timestamp    UserId    ItemId  count_item_apperances  \
2                6  1362062838  u0004598  i1411238                     43   
3                7  1362063503  u0031317  i1496422                    100   
4                5  1362063653  u0024257  i0118799                    102   
5                4  1362063879  u0024257  i0338013                    209   
7                8  1362064047  u0024257  i0064665                     28   
...            ...         ...       ...       ...                    ...   
336666           8  1421527966  u0028976  i2179136                    143   
336667          10  1421528061  u0009522  i1187043                    111   
336668           8  1421528114  u0034255  i0166924                     55   
336670           7  1421528203  u0023373  i2084970                    352   
336671           7  1421528215  u0030809  i0102510                     12   

        count_user_apperances  
2                         169  
3                          53  
4                         176  
5                         176  
7                         176  
...                       ...  
336666                     25  
336667                     20  
336668                     49  
336670                     72  
336671                      3  

[255173 rows x 6 columns]

In [10]:
ratings.set_index("UserId",inplace=True)
matrix = pd.DataFrame(index=pd.Index(ratings.index.unique().tolist()))
matrix


Empty DataFrame
Columns: []
Index: [u0004598, u0031317, u0024257, u0029372, u0006099, u0010095, u0017242, u0010520, u0011075, u0023684, u0022913, u0031559, u0023947, u0036706, u0026647, u0025692, u0011389, u0013666, u0019874, u0008425, u0008191, u0013845, u0029934, u0027423, u0011884, u0008999, u0001325, u0026571, u0014255, u0013565, u0023278, u0026015, u0028836, u0035624, u0018277, u0026281, u0029254, u0032369, u0005140, u0038536, u0001649, u0032381, u0027420, u0035119, u0033596, u0029066, u0009517, u0004257, u0027664, u0010181, u0030753, u0005214, u0017009, u0017279, u0028852, u0025304, u0000669, u0018458, u0021596, u0021072, u0029933, u0036192, u0011304, u0027885, u0037035, u0009240, u0002339, u0037685, u0029898, u0036756, u0007702, u0011339, u0010770, u0021110, u0017837, u0025306, u0002490, u0004381, u0027382, u0023267, u0002372, u0006380, u0022183, u0022092, u0007784, u0038403, u0011726, u0015774, u0000871, u0031610, u0018861, u0033564, u0037597, u0023188, u0035417, u0031314, u0003093, u0027652, u0021487, u0019242, ...]

[7574 rows x 0 columns]

In [11]:
import time
start_time = time.time()

for item in ratings["ItemId"].unique().tolist():
    predictions = ratings.loc[ratings["ItemId"] == item]["Prediction"]
    matrix[item] = predictions
# your code
time.time() - start_time

120.22694730758667

In [12]:
# item = "i0060196"
# predictions = ratings.loc[ratings["ItemId"] == item]["Prediction"]
# predictions

In [13]:
# matrix[item] = predictions

In [14]:
# ratings["count_item_apperances"] = ratings.groupby("ItemId")["ItemId"].transform('count')

In [15]:
# ratings["count_user_apperances"] = ratings.groupby("UserId")["UserId"].transform('count')

In [16]:
# ratings = ratings.loc[(ratings["count_item_apperances"] > 10) | (ratings["ItemId"].isin(targets["ItemId"].unique().tolist()))]

In [17]:
# ratings = ratings.loc[(ratings["count_user_apperances"] > 10) | (ratings["UserId"].isin(targets["UserId"].unique().tolist()))]

In [14]:
matrix

i1411238  i1496422  i0118799  i0338013  i0064665  i0884328  \
u0004598 -0.270968  0.000000  0.000000  0.000000  0.000000  0.000000   
u0031317  0.000000  1.019231  0.000000  0.000000  0.000000  0.000000   
u0024257  0.000000  0.000000 -0.725806 -1.725806  2.274194  0.000000   
u0029372  0.000000  0.000000  0.000000  0.000000  0.000000  1.790323   
u0006099  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
...            ...       ...       ...       ...       ...       ...   
u0033172  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
u0003117  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
u0012635  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
u0020391  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
u0026580  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          i0949731  i0319343  i1068680  i0376994  ...  i2937898  i0068575  \
u0004598  0.000000  0.000000  0.000000       0.0  ...       0.0       0.0   
u0031317  0.000000  0.000000  0.000000       0.0  ...       0.0       0.0   
u0024257  0.000000  0.000000  0.000000       0.0  ...       0.0       0.0   
u0029372  0.000000  0.000000  0.000000       0.0  ...       0.0       0.0   
u0006099 -1.105634 -0.105634  0.894366       0.0  ...       0.0       0.0   
...            ...       ...       ...       ...  ...       ...       ...   
u0033172  0.000000  0.000000  0.000000       0.0  ...       0.0       0.0   
u0003117  0.000000  0.000000  0.000000       0.0  ...       0.0       0.0   
u0012635  0.000000  0.000000  0.000000       0.0  ...       0.0       0.0   
u0020391  0.000000  0.000000  0.000000       0.0  ...       0.0       0.0   
u0026580  0.000000  0.000000  0.000000       0.0  ...       0.0       0.0   

          i2513092  i0086969  i0165361  i2717822  i0102598  i0884732  \
u0004598       0.0       0.0       0.0       0.0       0.0       0.0   
u0031317       0.0       0.0       0.0       0.0       0.0       0.0   
u0024257       0.0       0.0       0.0       0.0       0.0       0.0   
u0029372       0.0       0.0       0.0       0.0       0.0       0.0   
u0006099       0.0       0.0       0.0       0.0       0.0       0.0   
...            ...       ...       ...       ...       ...       ...   
u0033172       0.0       0.0       0.0       0.0       0.0       0.0   
u0003117       0.0       0.0       0.0       0.0       0.0       0.0   
u0012635       0.0       0.0       0.0       0.0       0.0       0.0   
u0020391       0.0       0.0       0.0       0.0       0.0       0.0   
u0026580       0.0       0.0       0.0       0.0       0.0       0.0   

          i3140100  i3093522  
u0004598       0.0       0.0  
u0031317       0.0       0.0  
u0024257       0.0       0.0  
u0029372       0.0       0.0  
u0006099       0.0       0.0  
...            ...       ...  
u0033172       0.0       0.0  
u0003117       0.0       0.0  
u0012635       0.0       0.0  
u0020391       0.0       0.0  
u0026580       0.0       0.0  

[7574 rows x 7266 columns]

In [13]:
matrix = matrix.apply(lambda x : x - x.mean(),axis=1).fillna(0)

In [15]:
user_item = matrix.to_numpy()

In [16]:
user_item

array([[-0.27096774,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  1.01923077,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -0.72580645, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [17]:
norm = np.reshape(np.linalg.norm(user_item , axis=0), (1,user_item.shape[1]) )
norm

array([[11.04122325, 14.92487564, 13.45074263, ...,  0.87170531,
         0.58247423,  2.07692308]])

In [18]:
norm.shape

(1, 7266)

In [32]:
norm_sum = norm * norm.T # elemem wise multply
norm_sum #divisor da similaridade

array([[121.90861075, 164.78888388, 148.51265225, ...,   9.62469296,
          6.43122797,  22.93177136],
       [164.78888388, 222.75191295, 200.75066113, ...,  13.01009338,
          8.6933554 ,  30.99781864],
       [148.51265225, 200.75066113, 180.92247743, ...,  11.72508381,
          7.83471092,  27.93615778],
       ...,
       [  9.62469296,  13.01009338,  11.72508381, ...,   0.75987015,
          0.50774588,   1.81046488],
       [  6.43122797,   8.6933554 ,   7.83471092, ...,   0.50774588,
          0.33927622,   1.20975416],
       [ 22.93177136,  30.99781864,  27.93615778, ...,   1.81046488,
          1.20975416,   4.31360947]])

In [33]:
item_times_item = user_item.T @ user_item # != m @ m.T
item_times_item


array([[121.90861075,   2.87917146,  -2.82167168, ...,   0.        ,
          0.        ,   0.        ],
       [  2.87917146, 222.75191295,  -1.21804414, ...,   0.        ,
          0.        ,   0.        ],
       [ -2.82167168,  -1.21804414, 180.92247743, ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   0.75987015,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.33927622,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   4.31360947]])

In [35]:
similarity = item_times_item/norm_sum
similarity #matriz de similaridades item X item

array([[ 1.        ,  0.01747188, -0.01899954, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.01747188,  1.        , -0.00606745, ...,  0.        ,
         0.        ,  0.        ],
       [-0.01899954, -0.00606745,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  1.        ]])

In [38]:
similarity.shape

(7266, 7266)

In [42]:
df = pd.DataFrame(np.random.randint(0,5,size=(4, 5)), columns=list('ABCDE'))
print (df)
a=df.to_numpy()
a*a

   A  B  C  D  E
0  0  2  4  3  3
1  4  1  0  2  4
2  3  0  1  0  2
3  4  2  4  1  1


array([[ 0,  4, 16,  9,  9],
       [16,  1,  0,  4, 16],
       [ 9,  0,  1,  0,  4],
       [16,  4, 16,  1,  1]])